
export interface RefferalProps {
    Adress: String,
    City: String,
    DOBdata: String,
    DateCreated: String,
    DesiredAmountOfFunding: String,
    DoTheyAlreadyHaveABusiness: String,
    Email: String,
    FirstName: String,
    Income: Number,
    LastName: String,
    Notes: String,
    OwnerID: String,
    OwnerName: String,
    Phone: Number,
    State: String,
    Status: String,
    WhatsMainPurposeOfFund: String,
    Zip: Number,
    creditReport: String,
    nameOfTheBusiness: String,
    __v: Number,
    _id: String
}
